name: LuzioMedia
favicon: null
layout_spectrum: 0.86812
typography_spectrum: 0.50609
title: 'Photography for Designers, Architects, Home Builders, Real Estate'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3445206608157605
  lightness: 0.457818771712482
  saturation: 0.6481047493871301
  rhythmicContrast: 0.8919530035927892
purpose: []
